In [7]:
import numpy as np

In [8]:
a=np.array([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])

In [9]:
a

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [10]:
b=np.array([[4,8,7],[3,1,5],[6,9,13]])

In [11]:
b

array([[ 4,  8,  7],
       [ 3,  1,  5],
       [ 6,  9, 13]])

In [12]:
b[2,0:2:1]

array([6, 9])

In [13]:
a.shape
b.shape

(3, 3)

In [14]:
a.shape

(4, 3)

In [15]:
c=np.array([[[4,41],[8,81],[7,71]],[[3,31],[1,11],[5,51]],[[6,61],[9,91],[13,131]]])

In [16]:
c

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [17]:
c.shape

(3, 3, 2)

In [18]:
a[1,0:3:1]

array([9, 3, 5])

In [19]:
a[0:5:1,2]  #slicing

array([ 4,  5, 17,  8])

In [20]:
a[:,2].shape

(4,)

In [21]:
a[:,-1:]

array([[ 4],
       [ 5],
       [17],
       [ 8]])

In [22]:
b[1:,1::1]

array([[ 1,  5],
       [ 9, 13]])

In [23]:
b[1:,0:1],c[1:,0:1]

(array([[3],
        [6]]),
 array([[[ 3, 31]],
 
        [[ 6, 61]]]))

In [24]:
x=[3,4,5]


In [25]:
x+5

TypeError: can only concatenate list (not "int") to list

In [26]:
a+5

array([[ 8, 13,  9],
       [14,  8, 10],
       [16, 20, 22],
       [24, 36, 13]])

In [27]:
a*3

array([[ 9, 24, 12],
       [27,  9, 15],
       [33, 45, 51],
       [57, 93, 24]])

In [28]:
a[0,0]=6
a

array([[ 6,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [29]:
a[0,:]=[30,40,50]
a

array([[30, 40, 50],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [30]:
a[0:,1]=[401,301,151,311]
a

array([[ 30, 401,  50],
       [  9, 301,   5],
       [ 11, 151,  17],
       [ 19, 311,   8]])

In [31]:
a[0:2,1:]=[[201,303],[404,505]]
a

array([[ 30, 201, 303],
       [  9, 404, 505],
       [ 11, 151,  17],
       [ 19, 311,   8]])

In [32]:
np.append(a,[[1,1,1]],axis=0) # zero to add row-wise

array([[ 30, 201, 303],
       [  9, 404, 505],
       [ 11, 151,  17],
       [ 19, 311,   8],
       [  1,   1,   1]])

In [33]:
np.append(a,[[1],[1],[1],[1]],axis=1) #zero to add row-wise

array([[ 30, 201, 303,   1],
       [  9, 404, 505,   1],
       [ 11, 151,  17,   1],
       [ 19, 311,   8,   1]])

In [34]:
a

array([[ 30, 201, 303],
       [  9, 404, 505],
       [ 11, 151,  17],
       [ 19, 311,   8]])

In [35]:
np.delete(a,1,0)

array([[ 30, 201, 303],
       [ 11, 151,  17],
       [ 19, 311,   8]])

In [36]:
np.delete(a,1,axis=1)

array([[ 30, 303],
       [  9, 505],
       [ 11,  17],
       [ 19,   8]])

In [37]:
a.shape

(4, 3)

In [38]:
a.size

12

In [39]:
a.reshape(6,2)

array([[ 30, 201],
       [303,   9],
       [404, 505],
       [ 11, 151],
       [ 17,  19],
       [311,   8]])

In [40]:
a.dtype

dtype('int32')

In [41]:
a1=np.array([3.5,3.,7.])
a1

array([3.5, 3. , 7. ])

In [42]:
a1.dtype

dtype('float64')

lhvoucogvog

In [43]:
a1.astype('uint16') #

array([3, 3, 7], dtype=uint16)

In [44]:
a.mean(axis=1)

array([178.        , 306.        ,  59.66666667, 112.66666667])

In [45]:
a.std(axis=1)

array([112.63214461, 214.02024826,  64.62885492, 140.31472561])

In [46]:
#nutshell
## we create arrays
#1.np.arrays()
#1.np.ones()
#1.np.zeros()
#1.np.arange()
#1.np.linespace()
#np.random.randint()
## arrays have some attributes and function


In [47]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
np.linspace(1,11,6)

array([ 1.,  3.,  5.,  7.,  9., 11.])

In [49]:
np.random.randint(1,15,[3,4])

array([[ 2,  9,  6,  9],
       [ 2, 12,  3,  8],
       [ 7,  2,  4,  6]])

In [50]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [55]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [59]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [66]:
list(range(1,11,1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [80]:

np.random.randint(1,6,1)

array([3])

In [89]:
np.random.randint(1,6,[4,3,2])

array([[[2, 5],
        [1, 1],
        [4, 3]],

       [[5, 2],
        [2, 4],
        [5, 3]],

       [[3, 4],
        [5, 1],
        [5, 2]],

       [[3, 5],
        [2, 4],
        [1, 2]]])

In [90]:
np.random.randint(31,6000,[4,3])

array([[  50, 5026, 2986],
       [5679, 5672, 5194],
       [1681,  777, 2975],
       [3118, 5387, 5455]])

In [107]:
np.random.seed(54)
np.random.randint(31,6000,[4,3])


array([[ 929, 3886, 5174],
       [3840, 3423, 2096],
       [5160, 5669, 4744],
       [3350, 4835, 3347]])

In [120]:
np.random.rand(3,4)

array([[0.19555639, 0.71252488, 0.81638996, 0.47105727],
       [0.26108617, 0.44061904, 0.20938295, 0.47290381],
       [0.23138279, 0.16117695, 0.21706215, 0.16071548]])

In [113]:
r=np.loadtxt('somedata.txt',dtype=str)
r

array(['hi', 'this', 'a', 'file', 'outside', 'python'], dtype='<U7')

In [115]:
r=np.loadtxt('moredata.txt')
r

array([[ 48.,  34.,  56.,  78.],
       [ 79.,  80., 104.,  22.]])

In [127]:
np.savetxt('new.txt' ,p,delimiter=',')